# Config file for automatic testing at travis-ci.org
language: python
before_script:
  - sleep 3
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install --editable .
script:
- pylint myprogram.py
