language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python check_system_setup.py
  - python get_https.py
  - python get_socks4.py
  - python get_socks5.py



