# Config file for automatic testing at travis-ci.org
language: python
before_script:
  - sleep 3
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script: python check_proxy.py


